### ISSUE TITLE
Support of ChaCha20 / Argon2 format

### ISSUE THREAD

**Issue by jeremie-H** [Narigo/keepass-diff#21]
Hello, Thanks for your utility
I miss only thing in your utility, it's the possibility to support ChaCha20 encryption with Argon2 format of the kdbx file.

I'll have to change the format of the two files before to test the diff, or i've got a error like this :
```
KDBX error: Database integrity error: Encountered an invalid KDF UUID: [xx, xx, xx, xx, xx, xx, xx, xx...]
```

**Comment by Narigo** [comment]
Thanks for your interest in this tool!

Could you provide a reproducer / test file for this kind of encryption?

`keepass-diff` uses [keepass-rs](https://github.com/sseemayer/keepass-rs) under the hood to open `.kdbx` files, so it's constrained to what is available there. This issue sounds like a feature request for the underlying library to me. Can you check whether `keepass-rs` is able to open these kind of files?

**Comment by jeremie-H** [comment]
Yes it's more a feature request i think :) 
keepass-rs is indeed unable to open these .kdbx :-)

**Comment by Narigo** [comment]
@jeremie-H could you add a feature request to [keepass-rs](https://github.com/sseemayer/keepass-rs) with a reproducer file?
I would like to close this issue here and track it there. When it's done there, we can update the dependency and release a new version of `keepass-diff`.

**Comment by jeremie-H** [comment]
Hello i've try again with my original files, and I can't reproduce it with your last version, i close this case ;)
Thanks for your tool !
