### ISSUE TITLE
keepass-diff seems to be slow

### ISSUE THREAD

**Issue by HLeithner** [Narigo/keepass-diff#22]
I tried keepass-diff on windows with two 1.5mb files on windows and it used one cpu with 100% but it seams there is no progress.

Normally the database is open with KeepassXC on this system within of 3-5 seconds.

And it seems that it took 5 minutes or so to get a panic about an incorrectkey.

Is this performance expected?

**Comment by Narigo** [comment]
I had the impression that it got slower in my tests when the underlying module was updated. I thought it would still suffice, but if this is making the tool stop working, this needs some more attention.

Could you test your files with an earlier version (tagged 0.2.0) if that is working? The older version does not support the verbose log format but maybe it can work for you? If it works, we should check how to improve this

**Comment by Narigo** [comment]
@HLeithner does the "Performance note" tip of `keepass-rs` help? https://github.com/sseemayer/keepass-rs#installation

It says to set `RUSTFLAGS` to improve performance: `export RUSTFLAGS='-C target-cpu=native'`

**Comment by HLeithner** [comment]
Sorry I totally missed your  comment... I get several 100 github messages per day so it seems it get lost... I try to check this tomorrow.

**Comment by Narigo** [comment]
> Sorry I totally missed your comment... I get several 100 github messages per day so it seems it get lost...

I feel you, no worries 😀

**Comment by HLeithner** [comment]
Ok I tested it now with version 0.2.1 to 1.0.0 doesn't change much but using the target-cpu native makes it usable.
You should mention this in your install script too. Thanks for your work

**Comment by Narigo** [comment]
Thanks for the heads-up! I'll add it to the README. It does improve the performance significantly even for the `run-tests.sh` script.
