### ISSUE TITLE
Panic after entering second password

### ISSUE THREAD

**Issue by kezz** [Narigo/keepass-diff#28]
I just got the following error after entering the second password:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { pos: 3815:1, kind: Syntax("Unexpected characters outside the root element: \u{7}") }', /home/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/keepass-0.4.5/src/xml_parse.rs:33:17
```

I'm on Ubuntu Budgie 20.04, using the latest version of everything (installed rust just for this utility). I don't have any malformed entries in my keepass databases; no empty titles, etc. I did a workaround by just exporting the databases and diffing the result, so I'm unlikely to return to keepass-diff unless I mess up my databases again, but I thought I'd report nonetheless!

**Comment by Narigo** [comment]
Hi @kezz thanks for the report - I suppose this is a problem of the module reading the KeePass files "[keepass-rs](https://github.com/sseemayer/keepass-rs/)". I haven't seen this issue before though: Do you have a reproducer .kdbx file that can be opened (without passwords or just with some test strings inside)?

My wild guess would be that your database is using some special field, icons, anything that might be an edge case that wasn't tested yet, so a reproducer would be really nice for that.

**Comment by kezz** [comment]
I'll see if I can figure out anything untoward in the database files and get back to you!

**Comment by Narigo** [comment]
@kezz did you have a chance to look into your database files?
I've also updated the keepass dependency to 0.4.7 and released keepass-diff version 1.1.0 now. Maybe try this new version first as there were some additional things being added that might be able to read files that it was unable before

**Comment by kezz** [comment]
Hey Narigo - I wasn't able to find the issue in the files as I couldn't really reproduce it. I had probably already fixed whatever problem there was with my database. 

I've just tested it on my database again and it all works fine, although I'm not sure if that's just because it's fixed now or that my database doesn't contain the thing that was breaking it in the first place. Happy for you to close this if you would like.

**Comment by Narigo** [comment]
Ok, thanks for the heads-up! Let's hope it was fixed thanks to the dependency updates :)
