### ISSUE TITLE
failed to select a version for the requirement `aesni = "^0.6"`

### ISSUE THREAD

**Issue by Donatzsky** [Narigo/keepass-diff#34]
Trying to install with `RUSTFLAGS="-C target-cpu=native" cargo install keepass-diff`, it fails with the following error:

```
error: failed to compile `keepass-diff v1.1.0`, intermediate artifacts can be found at `/tmp/cargo-installghkBKQ`

Caused by:
  failed to select a version for the requirement `aesni = "^0.6"`
  candidate versions found which didn't match: 0.99.99, 0.10.0, 0.9.0, ...
  location searched: crates.io index
  required by package `aes v0.3.2`
      ... which is depended on by `keepass v0.4.7`
      ... which is depended on by `keepass-diff v1.1.0`
```

**Comment by lwbt** [comment]
I have the same issue here on Ubuntu 18.04 and Ubuntu 21.04.

The last version I can use is 0.3.0 with:

```bash
RUSTFLAGS="-C target-cpu=native" cargo install --git https://github.com/Narigo/keepass-diff --tag 0.3.0
```

Can someone please look into this? I don't have that much experience with Rust.

**Comment by Narigo** [comment]
Thanks for reporting this @Donatzsky and @lwbt !

It looks like the `aes` package version `0.3.2` got yanked, which the underlying keepass library uses. You should still be able to add `--locked` with the command to install `keepass-diff` to make it possible to use that yanked package.

The proper fix would be to update `aes` to a newer version in the `keepass` dependency.

**Comment by Narigo** [comment]
I have updated the dependencies now after `keepass-rs` got a new release and fixed the breaking change. I'm closing this now as it should work now without the `--locked` flag again.

If you have time, please let me know whether it worked for you @Donatzsky and @lwbt or if there is still some issue this didn't address. Thanks!

**Comment by Narigo** [comment]
(Released / published version 1.1.1 for that to check!)

**Comment by lwbt** [comment]
Appears to be working on my Ubuntu 21.04 installation. Thanks.

**Comment by Narigo** [comment]
Thank you for checking! 🙂
