### ISSUE TITLE
Documentation issues and rust-free image

### ISSUE THREAD

**Issue by micgrivas** [Narigo/keepass-diff#53]
A. I want to use this tool, without installing RUST.
There is a command to create the docker image, which raises these two questions:
  -  Why don't you provide the image?
  -  The build command expects Containerfile.install. But there is no link to it. Using RUST we can get it, but then we won't need it.

B. In the last line of that page it says "please reach out!" but there is no link for how .

C.  I made the docker image with the following Dockerfile, but the outcome is huge:  a 1.6GB image  !! 
```
FROM rust:latest

RUN RUSTFLAGS="-C target-cpu=native" cargo install keepass-diff
```
Can there be some way to make it smaller?  If I use stages in the dockerfile, what should I keep in the last stage?  Directories, files?

**Comment by KevinKlinger** [comment]
Hi @micgrivas,

A: The Containerfile.install is part of this repository (see https://github.com/Narigo/keepass-diff/blob/main/Containerfile.install)
C: You'll see the 2 staged build in the containerfile.install. The build stage image will be around 1.6GB too, but it's only required to build keepass-diff. The image to use will be the **keepass-diff:custom-local** which is around 5MB in size. Once you have the **keepass-diff:custom-local** image, you can remove the 1.6GB image to free some space on your disk.

HTH

**Comment by dennisroczek** [comment]
@Narigo regarding a) iff you are unable (time, knowledge, doesn't matter) to read the code and if you trust open source, it doesn't matter if you build "something" or simply use the downloadable binary. The attackable vector is the same. For me, a working binary would be enough. But to get my multiple keepass files (duplicates created by dropbox because of having them opened on multiple computers at the same time) reduced, I simply built the tool without knowing any rust.

**Comment by Narigo** [comment]
@dennisroczek thanks for this perspective! You're right, if you're unable to understand the code and install instructions, it's probably a lot easier to "find" binaries at untrusted sources then.

I think we should make it a priority to create binaries automatically. I believe it could be done through GitHub actions and using GitHub releases to share it.

**Comment by abc2006** [comment]
same for me - i support this request for 100% - even if i just downloaded rust and built the tool. An ready-to-use binary was also my preference :)
Thank you!

**Comment by micgrivas** [comment]
Thank you very much for your responses, @narigo and  @KevinKlinger .
I would like also to thank you for the great tool. 
Yes, you are right, the file is there, in your repo. The reason for a part of my questions is that I had git-cloned an older version (I hope) by S. Seemayer, where there was no such file.  Checking your git-link against my git-config I noticed the difference.   

Thanks for the info about the stages. I had done the same myself, since in Seemayer's version there was no stage, as it missed the Container....install  file.

Regarding the code vs binary ... did anyone go through all the code to check if there is any trick? I am sure the vast majority will just install/run.  For that majority a binary would have helped. 
And, yes, github actions can arrange for it to be built automatically (as in repo, Actions, create your workflow).

**Comment by micgrivas** [comment]
For the readme (B),  as you understand I know what you meant and how to reach out. But not all your audience will.
