### ISSUE TITLE
Provide --no-password-a / --no-password-b flags

### ISSUE THREAD

**Issue by Narigo** [Narigo/keepass-diff#6]
With the update to keepass 0.3.3, keyfile authentication will be possible. If no passwords should be provided, it is not possible to say so via scripts right now.

Blocked by the upgrade to keepass 0.3.3.

- [x] Add `--no-password-a` flag
- [x] Add `--no-password-b` flag
- [x] Add `--no-passwords` flag

**Comment by caemor** [comment]
A general --no-passwords flag would be also great in that case.

**Comment by Narigo** [comment]
I've added this feature to the open PR now.
