### ISSUE TITLE
DatabaseIntegrity error when opening database

### ISSUE THREAD

**Issue by sleroq** [Narigo/keepass-diff#72]
I encountered an error while using the keepass-diff tool to compare two KeePassXC databases. Both databases open successfully in the KeePassXC app without any problems.

OS: NixOS 24.05pre558881.a9bf124c46ef (Uakari) x86_64
Command: `RUST_BACKTRACE=1 keepass-diff Safe-A.kdbx Safe-B.kdbx --same-password`
Output:
```
Password for both files: 
thread 'main' panicked at src/main.rs:122:18:
Error opening database A: DatabaseIntegrity(Xml(BadEvent { expected: "text containing a value", event: End("Name") }))
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: keepass_diff::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

 I will update this issue once I identify the problematic record.
 
 This issue seems to be similar to #57

**Comment by louib** [comment]
This is probably an issue with the [`keepass-rs` library](https://github.com/sseemayer/keepass-rs), so I suggest you open an issue there.

Also, I think @Narigo already started to work on a fix for this issue, see [here](https://github.com/sseemayer/keepass-rs/pull/180).

**Comment by sleroq** [comment]
Thank you for your reply!

**Comment by zuoliang0** [comment]
I'd like to ask if this issue has been fixed in keepass-diff. I noticed that it's already fixed at https://github.com/sseemayer/keepass-rs/pull/180.

I encountered this problem again today.
