### ISSUE TITLE
أعتقد أن المشكلة هي أنني نسيت إضافة علامة إلى Git التي تلتزم بإصدار 1.2.0. ما زلت بحاجة إلى إضافة هذا هنا. شكرا على التنبيه بالمناسبة @panicgh!

### ISSUE THREAD

**Issue by ghost** [Narigo/keepass-diff#74]

**Comment by ghost** [comment]
نسخة مكررة من #
```css

```

**Comment by Narigo** [comment]
Sorry @Abonaif123, I can only understand German or English. If someone can translate or if you can open a new issue in English, that would be very helpful. Thanks!
